// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ammrdduiozudwvwgdcfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbXJkZHVpb3p1ZHd2d2dkY2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjUwMDksImV4cCI6MjA3MzAwMTAwOX0.od2YmzcZzHAsfcDmuVPeN5V_uq4__xCDZa_l5l9sXnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});